site_name: Shut Up & Write
site_url: http://www.reddit.com/r/shutupandwrite
repo_url: https://github.com/ShutUpAndWrite/community-docs

pages:
- Philosophy: index.md
- Reddit: reddit.md
- IRC (Chat): irc.md
- TeamSpeak (Voice): teamspeak.md

theme: cerulean
