site_name: Shut Up & Write
site_url: http://www.reddit.com/r/shutupandwrite
repo_url: https://github.com/ShutUpAndWrite/community-docs

pages:
- ['index.md', 'Philosophy']
- ['reddit.md', 'Reddit']
- ['irc.md', 'IRC (Chat)']
- ['teamspeak.md', 'TeamSpeak (Voice)']

markdown_extensions:
    toc:
        permalink: True
    admonition:

theme: cerulean
